export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS";
export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";
//Sign up
export const SET_SIGNUP_USERTYPE = "SET_SIGNUP_USERTYPE";
export const GET_IDTYPE = "GET_IDTYPE"

//User
export const GET_USERBYID = "GET_USERBYID";

//COMPANY
export const GET_COMPANY = "GET_COMPANY";
export const ADD_COMPANY = "ADD_COMPANY";
export const EDIT_COMPANY = "EDIT_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";

//CATEGORY
export const GET_CATEGORY = "GET_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

//SUBCATEGORY
export const GET_SUBCATEGORY = "GET_SUBCATEGORY";
export const ADD_SUBCATEGORY = "ADD_SUBCATEGORY";
export const EDIT_SUBCATEGORY = "EDIT_SUBCATEGORY";
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY";

//PRODUCT
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTVIEW = "GET_PRODUCTVIEW";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

//POLICY
export const GET_POLICY = "GET_POLICY";
export const GET_POLICYBYID = "GET_POLICYBYID";
export const GET_POLICYVIEW = "GET_POLICYVIEW";
export const ADD_POLICY = "ADD_POLICY";
export const EDIT_POLICY = "EDIT_POLICY";
export const DELETE_POLICY = "DELETE_POLICY";

export const SET_PREMIUMCNT = "SET_PREMIUMCNT";
export const SET_PLANCNT = "SET_PLANCNT";
export const DELETE_PLANCNT = "DELETE_PLANCNT";
export const SET_AMOUNTCNT = "SET_AMOUNTCNT";
export const DELETE_AMOUNTCNT = "SET_AMOUNTCNT";

export const GET_PAYSCHEDULE = "GET_PAYSCHEDULE";

export const GET_COVERAMOUNT = "GET_COVERAMOUNT";
export const ADD_COVERAMOUNT = "ADD_COVERAMOUNT";
export const EDIT_COVERAMOUNT = "EDIT_COVERAMOUNT";
export const DELETE_COVERAMOUNT = "DELETE_COVERAMOUNT";

export const GET_MEMBERTYPE = "GET_MEMBERTYPE";

export const GET_OPTIONTYPE = "GET_OPTIONTYPE";
export const ADD_OPTIONTYPE = "ADD_OPTIONTYPE";
export const EDIT_OPTIONTYPE = "EDIT_OPTIONTYPE";
export const DELETE_OPTIONTYPE = "DELETE_OPTIONTYPE";

export const GET_AGEGROUP = "GET_AGEGROUP";
export const GET_MAIN_MEMBER = "GET_MAIN_MEMBER";
export const GET_POLICY_PREMIUM = "GET_POLICY_PREMIUM";
export const GET_POLICY_DEPENDENTS = "GET_POLICY_DEPENDENTS";

//BILLING OPTIONS

export const GET_TRANSACTION = "GET_TRANSACTION";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const EDIT_TRANSACTION = "EDIT_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";

export const GET_BANKACCOUNT = "GET_BANKACCOUNT";
export const ADD_BANKACCOUNT = "ADD_BANKACCOUNT";
export const EDIT_BANKACCOUNT = "EDIT_BANKACCOUNT";
export const DELETE_BANKACCOUNT = "DELETE_BANKACCOUNT";

//CONTACT 
export const GET_CONTACTLIST = "GET_CONTACTLIST";
export const GET_RELATIONSHIP = "GET_RELATIONSHIP";
export const GET_MODECOMMUNICATION = "GET_MODECOMMUNICATION";
export const GET_COUNTRY = "GET_COUNTRY";
export const GET_REGION = "GET_REGION";
export const GET_CIRCUIT = "GET_CIRCUIT";
export const GET_TEMPLE = "GET_TEMPLE";
export const GET_CIRCUITBYREGION = "GET_CIRCUITBYREGION";
export const GET_TEMPLEBYCIRCUIT = "GET_TEMPLEBYREGIONANDCIRCUIT";
export const GET_ADDRESSTYPE = "GET_ADDRESSTYPE";
export const GET_CURRENTCONTACT = "GET_CURRENTCONTACT";
export const GET_CONTACTADDRESSINFO = "GET_CONTACTADDRESSINFO";
export const GET_CONTACTINDENTIFICATION = "GET_CONTACTINDENTIFICATION";
export const GET_CONTACTDATA = "GET_CONTACTDATA";
export const SET_PREVIEWSTATUS = "SET_PREVIEWSTATUS";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const SET_CONTACTID = "SET_CONTACTID";
export const UPDATE_CURRENTCONTACT = "UPDATE_CURRENTCONTACT";
export const UPDATE_CONTACTADDRESSINFO = "UPDATE_CONTACTADDRESSINFO";
export const UPDATE_CONTACTINDENTIFICATION = "UPDATE_CONTACTINDENTIFICATION";

export const CREATE_CONTACTBASEINFO = "CREATE_CONTACTBASEINFO";
export const CREATE_CONTACTADDRESS = "CREATE_CONTACTADDRESS";
export const CREATE_CONTACTIDENTIFICATION = "CREATE_CONTACTIDENTIFICATION";


//UPDATE STATUS
export const SELECT_CAT = "SELECT_CAT";

//CONTACT PAGE STATUS
export const CHANGE_CONTACTPAGESTATUS = "CHANGE_CONTACTPAGESTATUS";

//SORT TABLE
export const SORT_DATA = "SORT_DATA";
